import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import ToastProvider from "../components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rapidise Practical Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>{children}</Providers>
        <ToastProvider />
        <footer className="bg-white text-black py-8 mt-auto">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col md:flex-row justify-between items-center">
              <div className="mb-4 md:mb-0">
                <h3 className="text-xl font-bold">Rapidise</h3>
                <p className="text-black mt-1">Innovating the future of technology</p>
              </div>            
            </div>
            <div className="mt-8 pt-8 border-t border-gray-700 text-center text-black">
              <p>&copy; {new Date().getFullYear()} Rapidise. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
